### ISSUE TITLE
#eventually doesn't work if rspec is loaded after capybara-ui in the Gemfile

### ISSUE THREAD

**Issue by shoe** [mojotech/capybara-ui#156]
We check for `defined?(RSpec)` in order to know whether or not to add RSpec's `ExpectationNotMet` exception to our list of exceptions to rescue inside an `eventually` block.  But, if RSpec hasn't been loaded yet, then we don't find it, and we don't ever try to rescue that exception.  Therefore, the `eventually` block just errors out the first time.

A solution might be to check for RSpec each time `eventually` is called.

**Comment by cpjolicoeur** [comment]
I'm actually already working on this.  Came across it on UW211. 

Talked with @david and I think a solution is to just have users manually require something like 

```ruby
require 'capybara/ui/rspec
```

on projects that they want RSpec support on.

I've started a branch already (yesterday actually) to start this

**Comment by aesnyder** [comment]
Love the rename of the repo. Makes a lot of sense.

**Comment by cpjolicoeur** [comment]
Fixed in #157
