### ISSUE TITLE
Ruby 2.7 deprecation warning - keyword parameter

### ISSUE THREAD

**Issue by thomasbalsloev** [mojotech/capybara-ui#167]
## Meta
Capybara Version: 3.35.3
Driver Information (and browser if relevant): selenium-webdriver 4.0.0.alpha7 with Google Chrome 88.0.4324.182 (headless)
Ruby: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
OS: Ubuntu 20.04
Rails: 6.0.3.5

## Expected Behavior
Should not display keyword parameter warning

## Actual Behavior
Displays several keyword parameter warnings. Example:

/usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/capybara-3.35.3/lib/capybara/session.rb:762: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call

Stacktrace:
`
/usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/capybara-3.35.3/lib/capybara/session.rb:762:in `find'
/usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/capybara-ui-1.2.0/lib/capybara/ui/widgets/widget/node_filter.rb:12:in `node'
/usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/capybara-ui-1.2.0/lib/capybara/ui/widgets/widget.rb:97:in `find_in'
/usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/capybara-ui-1.2.0/lib/capybara/ui/widgets/parts/container.rb:25:in `widget'
/usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/capybara-ui-1.2.0/lib/capybara/ui/dsl.rb:82:in `block in widget'
/usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/capybara-ui-1.2.0/lib/capybara/ui/checkpoint.rb:89:in `call'
/usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/capybara-ui-1.2.0/lib/capybara/ui/checkpoint.rb:63:in `wait_for'
/usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/capybara-ui-1.2.0/lib/capybara/ui/dsl.rb:99:in `eventually'
/usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/capybara-ui-1.2.0/lib/capybara/ui/dsl.rb:82:in `widget'
/var/www/portal/features/step_definitions/common/ui/utility_steps.rb:61:in `block in <top (required)>'
/usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/cucumber-5.3.0/lib/cucumber/glue/invoke_in_world.rb:36:in `instance_exec'
/usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/cucumber-5.3.0/lib/cucumber/glue/invoke_in_world.rb:36:in `block in cucumber_instance_exec_in'
/usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/cucumber-5.3.0/lib/cucumber/glue/invoke_in_world.rb:50:in `cucumber_run_with_backtrace_filtering'
/usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/cucumber-5.3.0/lib/cucumber/glue/invoke_in_world.rb:26:in `cucumber_instance_exec_in'
/usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/cucumber-5.3.0/lib/cucumber/glue/step_definition.rb:134:in `invoke'
/usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/cucumber-5.3.0/lib/cucumber/step_match.rb:33:in `invoke'
/usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/cucumber-5.3.0/lib/cucumber/runtime/support_code.rb:75:in `invoke_dynamic_step'
/usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/forwardable.rb:235:in `invoke_dynamic_step'
/usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/cucumber-5.3.0/lib/cucumber/glue/proto_world.rb:163:in `block (2 levels) in for'
/usr/local/rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/cucumber-5.3.0/lib/cucumber/glue/proto_world.rb:30:in `step'
/var/www/portal/features/step_definitions/dashboard/ui/utility_steps.rb:2:in `login_to_dashboard'
`

## Steps to reproduce
The problem arises here:

https://github.com/mojotech/capybara-ui/blob/master/lib/capybara/ui/widgets/widget/node_filter.rb#L41-L45

The "default" hash is added to the output and splatted to arg in this line:

https://github.com/mojotech/capybara-ui/blob/master/lib/capybara/ui/widgets/widget/node_filter.rb#L12

Exception occurs when the last hash elements is used as parameter, e.g. [:field, "user_email", {:wait=>0}].
The hash should be double splatted when used as argument, but is not.

Hope this helps.

Best regards, Thomas Balaløv.

**Comment by cpjolicoeur** [comment]
@thomasbalsloev Thanks for the bug report and detailed write-up/investigation.  Any chance you could file a quick Pull Request with a fix for this and we can get it out in a new release?

**Comment by thomasbalsloev** [comment]
@cpjolicoeur 

I'll try and give a shot next week.
